//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopuhDC.Data.Remote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDecision
    {
        public int Id { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderState OrderState { get; set; }
    }
}
